-- Reduz Instituição via dev
NDefines.NCountry.INSTITUTION_BONUS_FROM_IMP_DEVELOPMENT = 2
-- Knowledge Sharing não funciona mais
NDefines.NDiplomacy.KNOWLEDGE_SHARING_INSTITUTION_GROWTH_MONTHLY = 0
NDefines.NDiplomacy.KNOWLEDGE_SHARING_DURATION_YEARS = 0
NDefines.NDiplomacy.KNOWLEDGE_SHARING_COST_PERCENT_MONTHLY = 0
NDefines.NAI.DIPLOMATIC_ACTION_KNOWLEDGE_SHARING_ACCEPTANCE_MULT = 0
-- Alliances
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = -10
NDefines.NDiplomacy.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -125
-- AE
NDefines.NDiplomacy.PO_DEMAND_PROVINCES_AE = 0.8
-- Peace
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.PEACE_COST_DEMAND_PROVINCE = 1.0 -- default is 0.8